name: Rust Toolchain for Xtensa
description: Install the Rust compiler fork targeting Xtensa devices
author: esp-rs

branding:
  icon: play-circle
  color: red

inputs:
  default:
    description: Set installed toolchain as default
    default: false
  buildtargets:
    description: Comma separated list of targets
    default: all
  version:
    description: Which version of the toolchain to install
    default: latest
  ldproxy:
    description: Whether to install ldproxy (required for `std`)
    default: true
  override:
    description: Whether to override the toolchain
    default: true

runs:
  using: composite
  steps:
    - uses: taiki-e/install-action@v1
      with:
        tool: espup
    - uses: taiki-e/install-action@v1
      if: inputs.ldproxy == true
      with:
        tool: ldproxy
    - name: Install Xtensa toolchain
      shell: bash
      run: |
        [[ "${{ inputs.version }}" != latest ]] && version="--toolchain-version ${{ inputs.version }}" || version=""
        espup install -l debug --targets ${{ inputs.buildtargets }} $version
        [[ "${{ inputs.default }}" = true ]] && rustup default esp || true
        [[ "${{ inputs.override }}" = true ]] && rustup override unset || true
        source "$HOME/export-esp.sh"
        echo "$PATH" >>"$GITHUB_PATH"
        echo "LIBCLANG_PATH=${LIBCLANG_PATH}" >>"$GITHUB_ENV"
