name: Rust Toolchain for Xtensa
description: Install the Rust compiler fork targeting Xtensa devices
author: esp-rs

branding:
  icon: play-circle
  color: red

inputs:
  default:
    description: Set installed toolchain as default
    default: false
  buildtargets:
    description: Comma separated list of targets
    default: all
  version:
    description: Which version of the toolchain to install
    default: latest
  ldproxy:
    description: Whether to install ldproxy (required for `std`)
    default: true
  override:
    description: Whether to override the toolchain
    default: true

runs:
  using: composite
  steps:
    - name: Ensure that Rust is already installed
      shell: bash
      run: |
        if [ ! -d "$HOME/.cargo/bin" ]; then
          curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal -y
        fi

    - name: Install ldproxy
      if: inputs.ldproxy == 'true'
      shell: bash
      run: |
        curl -LO https://github.com/esp-rs/embuild/releases/latest/download/ldproxy-x86_64-unknown-linux-gnu.zip
        unzip -o ldproxy-x86_64-unknown-linux-gnu.zip -d "$HOME/.cargo/bin"
        chmod a+x "$HOME/.cargo/bin/ldproxy"

    - name: Install espup
      shell: bash
      run: |
        curl -L https://github.com/esp-rs/espup/releases/latest/download/espup-x86_64-unknown-linux-gnu -o "$HOME/.cargo/bin/espup"
        chmod a+x "$HOME/.cargo/bin/espup"

    - name: Install Xtensa toolchain
      shell: bash
      run: |
        source "$HOME/.cargo/env"
        [[ "${{ inputs.version }}" != latest ]] && version="--toolchain-version ${{ inputs.version }}" || version=""
        "$HOME/.cargo/bin/espup" install -l debug --export-file $HOME/exports --targets ${{ inputs.buildtargets }} $version
        source "$HOME/exports"
        echo "$PATH" >> "$GITHUB_PATH"
        echo "LIBCLANG_PATH=${LIBCLANG_PATH}" >> "$GITHUB_ENV"
        [[ "${{ inputs.default }}" = true ]] && rustup default esp || true
        [[ "${{ inputs.override }}" = true ]] && rustup override unset || true
