name: Rust Toolchain for Xtensa
description: Install the Rust compiler fork targeting Xtensa devices
author: esp-rs

branding:
  icon: play-circle
  color: red

inputs:
  default:
    description: Set installed toolchain as default
    default: false
  buildtargets:
    description: Comma separated list of targets
    default: all
  version:
    description: Which version of the toolchain to install in the form of '<major>.<minor>.<patch>.<subpatch>'. If no version is provided, 'latest' available version will be used
    required: false
  ldproxy:
    description: Whether to install ldproxy (required for `std`)
    default: true
  override:
    description: Whether to override the toolchain
    default: true

runs:
  using: composite
  steps:
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: ${{ inputs.override }}
    - name: Install Xtensa toolchain
      shell: bash
      run: |
        [[ "${{ inputs.ldproxy }}" = true ]] && crates="ldproxy" || crates=""
        ${{ github.action_path }}/install.sh "$crates" ${{ inputs.version }} ${{ inputs.buildtargets }}
        [[ "${{ inputs.default }}" = true ]] && rustup default esp || true
        [[ "${{ inputs.override }}" = true ]] && rustup override unset || true
